### ISSUE TITLE
Broken on Julia 1.0+

### ISSUE THREAD

**Issue by boathit** [JuliaML/MLDatasets.jl#26]
It seems that the package is broken on OS X with Julia 1.0+, but it works normally on Linux.

```julia
train_x, train_y = MNIST.traindata() # throws an error when trying to download the dataset

Do you want to download the dataset from ["http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz", "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz", "http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz", "http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz"] to "/Users/fineday/.julia/datadeps/MNIST"?
[y/n]
y
ERROR: UndefVarError: GET not defined
Stacktrace:
 [1] (::getfield(Base, Symbol("##683#685")))(::Task) at ./asyncmap.jl:178
 [2] foreach(::getfield(Base, Symbol("##683#685")), ::Array{Any,1}) at ./abstractarray.jl:1835
 [3] maptwice(::Function, ::Channel{Any}, ::Array{Any,1}, ::Array{String,1}) at ./asyncmap.jl:178
 [4] wrap_n_exec_twice at ./asyncmap.jl:154 [inlined]
 [5] #async_usemap#668(::Int64, ::Nothing, ::Function, ::getfield(DataDeps, Symbol("##14#15")){typeof(DataDeps.fetch_http),String}, ::Array{String,1}) at ./asyncmap.jl:103
 [6] #async_usemap at ./none:0 [inlined]
 [7] #asyncmap#667 at ./asyncmap.jl:81 [inlined]
 [8] asyncmap at ./asyncmap.jl:81 [inlined]
 [9] run_fetch at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution_automatic.jl:104 [inlined]
 [10] #download#13(::Array{String,1}, ::Nothing, ::Bool, ::Function, ::DataDeps.DataDep{String,Array{String,1},typeof(DataDeps.fetch_http),typeof(identity)}, ::String) at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution_automatic.jl:78
 [11] download at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution_automatic.jl:70 [inlined]
 [12] handle_missing at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution_automatic.jl:10 [inlined]
 [13] _resolve(::DataDeps.DataDep{String,Array{String,1},typeof(DataDeps.fetch_http),typeof(identity)}, ::String) at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution.jl:83
 [14] resolve(::DataDeps.DataDep{String,Array{String,1},typeof(DataDeps.fetch_http),typeof(identity)}, ::String, ::String) at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution.jl:29
 [15] resolve(::String, ::String, ::String) at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution.jl:54
 [16] resolve at /Users/fineday/.julia/packages/DataDeps/CDQwy/src/resolution.jl:73 [inlined]
 [17] #2 at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/download.jl:17 [inlined]
 [18] withenv(::getfield(MLDatasets, Symbol("##2#3")){String,Nothing}, ::Pair{String,String}) at ./env.jl:148
 [19] with_accept at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/download.jl:10 [inlined]
 [20] #datadir#1 at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/download.jl:14 [inlined]
 [21] datadir at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/download.jl:14 [inlined]
 [22] #datafile#4(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String, ::String, ::Nothing) at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/download.jl:32
 [23] datafile at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/download.jl:32 [inlined]
 [24] #traintensor#2 at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/MNIST/interface.jl:54 [inlined]
 [25] #traintensor at ./none:0 [inlined]
 [26] #traindata#10 at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/MNIST/interface.jl:231 [inlined]
 [27] #traindata at ./none:0 [inlined]
 [28] #traindata#11 at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/MNIST/interface.jl:235 [inlined]
 [29] traindata() at /Users/fineday/.julia/packages/MLDatasets/yNB45/src/MNIST/interface.jl:235
 [30] top-level scope at none:0
```

**Comment by Evizero** [comment]
cc @oxinabox

**Comment by oxinabox** [comment]
Hmmm,
We may need to adjust some compact somewhere.
Can you upload you'd Manifest.toml?

**Comment by oxinabox** [comment]
Hmmm,
We may need to adjust some compact somewhere.
Can you upload you'd Manifest.toml?

**Comment by boathit** [comment]
Yeah, sure. You can find it [here](https://drive.google.com/file/d/1jq8iP745XC05k59fqwRn5RUhvOdX1CXQ/view?usp=sharing).

**Comment by arrufat** [comment]
I'm also experiencing this exact same problem on Arch Linux, Here is my [Manifest.toml](https://gist.github.com/arrufat/5537999a64a72b9494509db6c97def9d)

**Comment by oxinabox** [comment]
Hmm, 
So DataDeps v0.6+ 
requires HTTP.jl v0.7+
as per 
https://github.com/oxinabox/DataDeps.jl/blob/12a2a27f8bdf88698c1593121cfab06e01c8c7b7/Project.toml#L14


But for some reason @boathit  and @arrufat 's Manifest.toml has

```
[[DataDeps]]
deps = ["DelimitedFiles", "HTTP", "Reexport", "SHA", "Test"]
git-tree-sha1 = "3c2f8ee0ec7bbf1a76a8e2fc1998a123e51f5791"
uuid = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
version = "0.6.1"
...
[[HTTP]]
deps = ["Base64", "Dates", "Distributed", "IniFile", "MbedTLS", "Sockets", "Test"]
git-tree-sha1 = "8a0f75e8b09df01d9f1ba9ad3fbf8b4983595d20"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.6.14"
```


Which I don't understand how that is possible.
but running `] resolve` or `] up` should fix it I think.

**Comment by oxinabox** [comment]
So apparently the problem is that Project.toml is actually ignored still,
and the DataDeps.jl REQUIRE needs to be updated to say HTTP 0.7

**Comment by CarloLucibello** [comment]
If no one is still experiencing the problem, we could close the issue

**Comment by oxinabox** [comment]
I think I fixed it in DataDeps.
Are you still suffering it?
